_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 100
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 100
                - 105
            "3":
                - 2
                - 13
                - 23
                - 55
                - 62
            "4": 3.11.9
            "5": 0.19.7
            "6": 4.49.0
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
cli_configs:
    value:
        batch_size: "8"
        batch_sizes: []
        bootstrap_iters: 100000
        device: cuda
        fewshot_seed: 1234
        gen_kwargs: null
        limit: null
        model: huggingface
        model_args: pretrained=nlptown/bert-base-multilingual-uncased-sentiment,max_length=512,truncation=True,cache_dir=hf_cache
        model_dtype: torch.float32
        model_num_parameters: 167463831
        model_revision: main
        model_sha: 8f6f4e3a8f70be4b65d3a4a8762b6d781cda240d
        numpy_seed: 1234
        random_seed: 0
        torch_seed: 1234
        use_cache: null
task_configs:
    value:
        openbookqa:
            dataset_name: main
            dataset_path: openbookqa
            description: ""
            doc_to_choice: '{{choices.text}}'
            doc_to_decontamination_query: question_stem
            doc_to_target: '{{choices.label.index(answerKey.lstrip())}}'
            doc_to_text: question_stem
            fewshot_delimiter: |4+

            metadata:
                version: 1
            metric_list:
                - aggregation: mean
                  higher_is_better: true
                  metric: acc
                - aggregation: mean
                  higher_is_better: true
                  metric: acc_norm
            num_fewshot: 5
            output_type: multiple_choice
            repeats: 1
            should_decontaminate: true
            target_delimiter: ' '
            task: openbookqa
            test_split: test
            training_split: train
            validation_split: validation
